OpenAI_key = "your OpenAI key"
whitelist = ["sally", "bob", "joe"]

[database]
host = 'synology.yunnote.cn'
port = 23306
user = 'score'
password = 'ssXzdvb$^F6WYX'
db = 'student_management'
charset = 'utf8mb4'
